---
title: "R Notebook"
output: html_notebook
---

```{r}
getwd()
```

```{r}
library(reshape)

cov <- read.table("./hg002_aligned_against_IGH/sorted.hg002_on_igh_106879844-105586437.coverage.minimap",
         header=FALSE, sep="\t", na.strings="NA", dec=".", strip.white=TRUE)
cov<-rename(cov,c(V1="Chr", V2="locus", V3="depth"))

```


```{r}
counts <- table(cov$depth)
head(counts, 10)
```


```{r}
hist(cov$depth)
```
```{r}
plot(cov$locus, cov$depth, ylim=c(0,5))
```
```{r}
plot(cov$locus, cov$depth, ylim=c(0,5), xlim=c(400000,500000))
```


```{r}
library(reshape)

cov_lra <- read.table("sorted.hg002_jan10_on_igh_GRCh38.coverage.lra",
         header=FALSE, sep="\t", na.strings="NA", dec=".", strip.white=TRUE)
cov_lra<-rename(cov_lra,c(V1="Chr", V2="locus", V3="depth"))

```

```{r}
counts <- table(cov_lra$depth)
head(counts, 10)
```
```{r}
hist(cov_lra$depth)
```
```{r}
plot(type="l",cov_lra$locus, cov_lra$depth)
```
```{r}
library(reshape)

cov_lra2 <- read.table("sorted.hg002_jan10_on_igh_GRCh38.coverage.all_bases",
         header=FALSE, sep="\t", na.strings="NA", dec=".", strip.white=TRUE)
cov_lra2<-rename(cov_lra,c(V1="Chr", V2="locus", V3="depth"))

```

```{r}
counts <- table(cov_lra2$depth)
head(counts, 10)
```
```{r}
hist(cov_lra2$depth)
```
```{r}
plot(type="l",cov_lra2$locus, cov_lra2$depth)
```